SELECT P.PACKAGE_ID, P.PACKAGE_NAME, P.PACKAGE_COMMAND, P.PACKAGE_DESCRIPTION
	FROM PACKAGE P JOIN PACKAGE_ENV_RELATION PE 
	ON (P.PACKAGE_ID = PE.PACKAGE_ID)
	WHERE PE.ENV_ID = 2

--This is for selecting the packages for a given env. Substitute 2 for env id
